# The URL the site will be built for
base_url = "https://jonhikes.com"

title = "Jon Hikes"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
feed_filename = "rss.xml"
smart_punctuation = false
author = "Jon Carl"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
